### ISSUE TITLE
MessageTrait::withHeader does not check for existing header names

### ISSUE THREAD

**Issue by pdscopes** [zendframework/zend-diactoros#100]
Not a massive issue but when when calling ```withHeader``` there is no check for an existing header name inside ```$this->headers```. This means that the newly Message created message could have a duplicated property. This can only occur when the added header name has a different capitalisation than the already stored header of the same name. i.e.:

```
// Assume there is a response message called $response
// Also assume that $response has a header set 'Content-Type' => ['application/json']
$new = $response->withHeader('Content-type', ['text/html']);
```

```$new``` will have one value in the ```$this->headerNames``` map but 'Content-Type' and 'Content-type' in ```$this->headers```.

A potential solution is to perform a ```$this->hasHeader($name)``` check and unsetting that header value if true _before_ setting the value in ```$new```.

**Comment by Maks3w** [comment]
I confirm getHeaders will return old and new headers 

Could you send a PR with the fix?

**Comment by pine3ree** [comment]
Another solution could be using the normalized header name for the $headers property of  MessageTrait but it would require many more changes: 
- withHeader(...)
```php
public function withHeader($name, $value)
{
    //...
    $normalized = strtolower($name);

    $new = clone $this;
    $new->headerNames[$normalized] = $name;
    $new->headers[$normalized]     = $value;

    return $new;
}
```
- withAddedHeader(...)
```php
public function withAddedHeader($name, $value)
{
    //...
    $normalized = strtolower($name);

    $new = clone $this;
    $new->headers[$normalized] = array_merge($this->headers[$normalized], $value);

    return $new;
}
```
- getHeaders() methods : fetch the original case $name from $headerNames in instead of simply returning the $headers property 
```php
public function getHeaders() 
{
    $headers = [];
    foreach ($this->headers as $name => $value) {
        $headers[$this->headerNames[$name]] = $value;
    }

    return $headers;
}
```
- getHeader(...) methods: here it won't be needed to fetch the original header name anymore
```php
public function getHeader($name)
{
    if (! $this->hasHeader($name)) {
        return [];
    }

    $value  = $this->headers[strtolower($name)];
    $value  = is_array($value) ? $value : [$value];

    return $value;
}
```

... and so on...
This is how I implemented by http library as per my interpretation psr-7 case insensitivity of header names when requesting their values: to me it seemed more natural to use the original names array only when requesting all the headers from the message as per psr-7 request and since there cannot be duplicate values for the same case-insensitive name it sounded logical to have normalized names for the $headers (values) property keys.
But of course @pdscopes' solution of unsetting existing header is much more simpler for how diactoros is implemented.

kindl regards

**Comment by pdscopes** [comment]
@pine3ree, I like your solution. Although it is a bigger change to the code base, it is man overall simpler solution.

**Comment by weierophinney** [comment]
@pine3ree — PSR-7 indicates that the return value of `getHeaders()` should have the header names *in the original case* with which they were registered. Only `getHeader()`, `getHeaderLine()`, and `hasHeader()` act in a case-insensitive manner. How the library manages that is an implementation detail. We chose in Diactoros to have the array containing all header values have the case sensitive set, and a lookup map with the normalized => case sensitive version as it's relatively performant and prevents the need to re-map when `getHeaders()` is called.

@pdscopes — patch looks good; will review for merge soon.

**Comment by pine3ree** [comment]
@pdscopes I agree.. :-) as I explained in my comment, your solution is undoubtedly the correct choice for diactoros impementation. I was merely explaining my personal approach which has two opposite side effects: 
1. no need to unset headers with the same normalized names as they are overwritten by assignment; 
...but also...
2. the need of fetching the original names from the headerNames array in order to build and return a psr-7 compliant map.

kind regards

**Comment by pine3ree** [comment]
@weierophinney :+1:
