### ISSUE TITLE
Host Request header misses port number for SSL connections

### ISSUE THREAD

**Issue by basz** [zendframework/zend-diactoros#152]
It seems the Host header calculated without a port number when the Request contains these values.

```
'REQUEST_SCHEME' => 'https',
...
'SERVER_PORT' => '443',
...
'HTTP_HOST' => 'some-domain.localhost',
...
'HTTPS' => 'on',
```

Host should be known as : `some-domain.localhost:443`

but is known as : `some-domain.localhost`

see https://github.com/neomerx/cors-psr7/issues/12

dump of $request https://gist.github.com/basz/0408e7e72d4458afb008

**Comment by samsonasik** [comment]
@basz I've created PR https://github.com/zendframework/zend-diactoros/pull/310 for it

**Comment by weierophinney** [comment]
@basz I'm afraid I still do not understand the rationale behind this.

When I reviewed the original thread over on the neomerx/cors-psr7 repo, it looks like I may have misread an example when providing my last reply. You had noted that the scheme was HTTPS, over port 443, and that the `HTTP_HOST` entry in `$_SERVER` only included the hostname, and suggested that the `Host` header in the Diactoros request should include the port information, citing RFC-2616.

That specification does indeed state the following:

> A "host" without any trailing port information implies the default port for the service requested (e.g., "80" for an HTTP URL).

However, PSR-7 targets [RFC 7230](https://tools.ietf.org/html/rfc723), where the relevant section on the `Host` header is [section 5.4](https://tools.ietf.org/html/rfc7230#section-5.4). RFC 7230 **does not** indicate that the default port is 80 if not provided. In fact, sections [2.7.1](https://tools.ietf.org/html/rfc7230#section-2.7.1) and [2.7.2](https://tools.ietf.org/html/rfc7230#section-2.7.2) explicitly note that when the port is absent, the default _associated with the scheme_ is assumed.

As such, unless the `Host` header you receive contains the port information, then what Diactoros does currently _is correct per both PSR-7 and RFC 7230_, and I'd argue that neomerx/cors-psr7 is incorrect.

The reason for my push-back on this is that it makes a special case out of one of the default cases (no port information provided, using a standard scheme), and breaks existing semantics (no port provided for when the port matches the default port for the scheme). I anticipate later users providing a patch that wants to revert the behavior, and that leaves us then with a conflict between use cases. Since the specifications cover this, I'd prefer to defer to those and leave the behavior as-is.

**Comment by basz** [comment]
Let’s close this then.

- Not using neomerx anymore
- Issue is old
- We’re following standards

@weierophinney @samsonasik thanks
