### ISSUE TITLE
Streams are "rewind" by default, preventing writing to it

### ISSUE THREAD

**Issue by mnapoli** [zendframework/zend-diactoros#195]
All response classes have a `rewind()` call when creating the stream:

```php
$body = new Stream('php://temp', 'wb+');
$body->write($html);
$body->rewind();
```

This example is in [`HtmlResponse`](https://github.com/zendframework/zend-diactoros/blob/master/src/Response/HtmlResponse.php#L71).

That makes subsequent writes fail:

```php
$response = new TextResponse('Hello');
$response->getBody()->write(' world');
var_dump($response->getBody()->__toString());
```

This will show ` world`.

Is this intentional? It sounds really weird to me, because of this I can write to the response in middlewares because it will overwrite the controller's (or next middleware) response. It makes those responses almost unusable with middlewares, maybe I'm missing something?

I have searched through previous issues but only found pull requests that added the `rewind()` call with no explanation.

**Comment by weierophinney** [comment]
> Is this intentional?

Yes. The reason is because *most* streams used in a server context (and Diactoros is really aimed primarily at server-side) are write-once, and will only ever be read (in order to be emitted back to the client). As such, they should be in a state where they may be able to be emitted immediately.

That said, `__toString()` performs a `rewind()` as part of its logic, so it's entirely possible for us to remove this from the constructor.

If you want to append to a stream, likely the safest way to do that is to seek to the end of the stream before writing:

```php
if (! $stream->eof()) {
    $stream->seek($stream->getSize());
}
$stream->write(/* ... */);
```

In all honesty, you should likely always do this when writing, unless you're okay with overwriting or confident you're already at the end of the stream. (Either that, or replace the stream entirely.)

**Comment by mnapoli** [comment]
:+1: thanks, I'll do that.

This is also an issue when writing test, the `TextResponse` class is super useful to have a response for testing middlewares. That's a really specific issue though, I'll create a specific class for that.
