### ISSUE TITLE
Parsing a JSON ServerRequest

### ISSUE THREAD

**Issue by designermonkey** [zendframework/zend-diactoros#217]
Is there a simple way to have a server created based on a JSON ServerRequest?

I have the content type header correctly set, and have passed JSON in the body, yet `getParsedBody` is blank.

Any help would be appreciated, as I am having to jump through holes to do this before I create a server instance, which means lots of logic.

**Comment by weierophinney** [comment]
The method is called `getParsedBody()` precisely because the body typically needs to be _parsed_ before you can populate that data.

As such, you typically deal with this by having middleware that parses the request body. One such example is [in the zend-expressive-helpers package](https://github.com/zendframework/zend-expressive-helpers/blob/35126f5c7b71d56d5f1c18316d0bb67eef07aad9/src/BodyParams/BodyParamsMiddleware.php). That middleware registers two strategies by default, one for normal form-encoded submissions, another for JSON; based on the `Content-Type` header, it chooses the one to use. (You can also register other strategies if necessary.)

**Comment by designermonkey** [comment]
Thanks for the pointer there, I will check that package out :)
