### ISSUE TITLE
[Question] Why redefine the "getHeaders()" and "getHeader()" in Request.php ?

### ISSUE THREAD

**Issue by ncou** [zendframework/zend-diactoros#277]
Hi,

I was looking at the code and i got a question.

- The Request class, use the RequestTrait and MessageTrait.
- The 2 functions : getHeaders and getHeader are defined in the Request class, to hande the case for the "host" header.
- But there is already a getHeaders and getHeader functions in the messageTrait class, and the case about the "host" is already taken care in the initialize() function in the RequestTrait line68.

https://github.com/zendframework/zend-diactoros/blob/master/src/RequestTrait.php#L68

It seems to me the redefinig of the 2 functions in the request class is useless.

It looks like some old code, or am I missing something ?

**Comment by weierophinney** [comment]
You're missing something. :smile:

`RequestTrait` is used by both `Request` and `ServerRequest`; the latter _does not_ extend from the former, however, but does use `RequestTrait` to get common behavior, which includes the `initialize()` method.

The reason that `getHeaders()` and `getHeader()` differ in `Request` is because that implementation targets _clients_, where a `Host` header is required, and the logic in these methods is used to ensure it is populated. While this logic is also in the `initialize()` method, because a request can be built iteratively, having the logic in these two methods ensures that if we populate the URI later, but not the `Host` header, we'll still have a `Host` header to present to the client.

In server-side requests, the header is not required (though its absence is unlikely). Having the logic in the `initialize()` method ensures it's present if the URI contains it.
