### ISSUE TITLE
Question about fromStream serialization of Request 

### ISSUE THREAD

**Issue by mmenozzi** [zendframework/zend-diactoros#284]
Hi,
is there a reason why the `fromStream` deserialization method requires a "seekable" stream?  A network socket stream is not seekable if I'm not wrong so it's impossibile to deserialize request from a network stream.

https://github.com/zendframework/zend-diactoros/blob/754a2ceb7ab753aafe6e3a70a1fb0370bde8995c/src/Request/Serializer.php#L55

**Comment by Xerkus** [comment]
I suppose it is done because of this:
https://github.com/zendframework/zend-diactoros/blob/754a2ceb7ab753aafe6e3a70a1fb0370bde8995c/src/AbstractSerializer.php#L117-L118

If stream is not seekable and its pointer is moved (eg by further reading), then decorating stream would be unusable. `php://input`is seekable and for network sockets you would need to read them into memory or temp stream first.

**Comment by mmenozzi** [comment]
Thank you @Xerkus but I am not sure to understand. Could you please provide an example about using the deserialization with a network stream that is first red into memory or temp?

**Comment by joelwurtz** [comment]
Look at https://github.com/php-http/message/blob/master/src/Stream/BufferedStream.php which transform any not seekable stream into a seekable one

**Comment by mmenozzi** [comment]
Many thanks @joelwurtz.
