### ISSUE TITLE
Return types inaccurate

### ISSUE THREAD

**Issue by ged15** [zendframework/zend-diactoros#335]
First of all, thanks for this stellar package!

I just upgraded to v2 and I am facing a difficulty regarding return types. For example, `\Zend\Diactoros\MessageTrait::withBody()` returns `\Psr\Http\Message\MessageInterface` according to the return type, but `static`, according to the doc-block. Because of this combination, PHPStan gets confused with the following code:

```php
    public function exportAsExcelAction($profileId): \Psr\Http\Message\ResponseInterface
    {
        return (new Response())->withBody($output);
    }
```

`exportAsExcelAction()` is supposed to return `\Psr\Http\Message\ResponseInterface` but returns whatever `\Zend\Diactoros\MessageTrait::withBody()` returns and that is `\Psr\Http\Message\MessageInterface` according to the return type.

I think, that declaring the return type as `\Psr\Http\Message\MessageInterface` is incorrect. Even though, it does not cause issues when running the code, it causes issues with static analysis.

Would you consider removing those return type and just keeping the `static` return type of the doc-block? If so, I can a PR to do this.

**Comment by Xerkus** [comment]
Either way, php does not support covariance for return types nor contravariance for parameter types. So we have to live with what we have.
Tools might get confused, they are not perfect. Removing return type declaration for their sake would be a wrong move, so I am going to close this as a won't fix.

**Comment by ged15** [comment]
I tend to agree, but claiming that `\Zend\Diactoros\MessageTrait::withBody()` returns `\Psr\Http\Message\MessageInterface` is inaccurate and it seems to have been done just for the sake of code reuse - in this cast using `MessageTrait`.

**Comment by Xerkus** [comment]
Trait provides implementation for the `Psr\Http\Message\MessageInterface` interface with the signature it would have had should PSR-7 be accepted a bit later to target php 7 and above. Even without the trait we would be required to typehint against MessageInterface to stay in line with php limitations. As you can see, it is done this way not because of trait or code reuse, but because of implied interface contract.

Furthermore, should `psr/htp-message` ever see 2.0 release, it will have those typehints in place and zend-diactoros will just stay compatible.

If you would like to discuss it more, feel free to join our [chat](https://zendframework.slack.com/) ([signup here](https://zendframework-slack.herokuapp.com/)).

**Comment by Xerkus** [comment]
@ged15 FYI [PSR-17: HTTP Factories](https://www.php-fig.org/psr/psr-17/) was accepted, interfaces are available in composer package `psr/http-factory` and implementation for them is already available in zend-diactoros 2.
No need to use diactoros in our code directly. I am going to switch my code soon too.
