### ISSUE TITLE
Request stack?

### ISSUE THREAD

**Issue by anlutro** [zendframework/zend-diactoros#69]
I'm working on converting some projects from `symfony/http-foundation` to PSR7.

It implements a class named RequestStack (documented [here](http://symfony.com/blog/new-in-symfony-2-4-the-request-stack) and [here](http://api.symfony.com/2.7/Symfony/Component/HttpFoundation/RequestStack.html)), which classes that span multiple requests/subrequests could use to get the current request.

Is this something that could be within the scope of this package?

**Comment by weierophinney** [comment]
No.

`RequestStack` is an implementation detail of a particular workflow, and would be better suited at a level above PSR-7. As an example, [Stratigility](https://github.com/zendframework/zend-stratigility) implements request and response decorators that track the original incoming request and response; these still implement the PSR-7 interfaces, but add stack-like functionality so that lower layers in the middleware can get at the original instances. I would recommend a similar approach.

**Comment by anlutro** [comment]
I see. I might just use that package. Thanks for the reply!
