### ISSUE TITLE
UploadedFile::writeFile being called without stream

### ISSUE THREAD

**Issue by ahundiak** [zendframework/zend-diactoros#82]
On my windows xampp system using the builtin php server, PHP_SAPI is 'cli-server'

This causes UploadedFile::moveTo to call writeFile without a stream being created resulting in 

    Call to a member function rewind() on a non-object for $this->stream->rewind();

If in my controller I do:

    $file = $request->getUploadedFiles()['file'];
    $file->getStream(); // Causes a stream to be created, otherwise get exception
    $file->moveTo('someplace');

Then all is well.  

The fix will be easy but I'm not sure of the reasoning behind the switch statement in moveTo.  I'll be glad to submit a pull request but should moveTo() be fixed or writeFile()?  

It seems like move_uploaded_file should be used if $this->file is set but there is clearly more going on.

**Comment by weierophinney** [comment]
> I'm not sure of the reasoning behind the switch statement in moveTo

The switch exists to allow the implementation to work in both SAPI environments (e.g., Apache, FastCGI) as well as non-SAPI environments (e.g. cli-server, ReactPHP). In non-SAPI environments, `is_uploaded_file()` and `move_uploaded_file()` do not have defined behavior, and are not guaranteed to work.

> should moveTo() be fixed or writeFile()?

In this case, I'd say `writeFile()`; it should be calling `getStream()` to get the stream.

Since there's no easy way to test it, I'll go ahead and submit a fix.
