### ISSUE TITLE
withFragment() deviates from PSR-7

### ISSUE THREAD

**Issue by DASPRiD** [zendframework/zend-diactoros#93]
Looking at the following code-part:

https://github.com/zendframework/zend-diactoros/blob/6eb97f29abfcf14358da60f36917904315489c61/src/Uri.php#L627-L629

PSR-7 does not say that a leading hash must be removed from the fragment. I'm not quite sure, but theoretically, an encoded leading hash sign is valid in a fragment?

**Comment by weierophinney** [comment]
That removal is internal, so that we can store the value of the fragment, not the separator itself.

`#` is equivalent to not having it present, so I'm unsure what use it would be to store the fact that an empty fragment was present, other than to ensure you get back the exact same URI. Is this important?

**Comment by DASPRiD** [comment]
Well, technically a fragment may start with an encoded hash-sign.

**Comment by DASPRiD** [comment]
To clarify, When doing this:

```
$uri = new Uri('http://example.com/');
echo $uri->withFragment('#test');
```

This should output:
`http://example.com/#%23test`

**Comment by weierophinney** [comment]
@DASPRiD would you be willing to create a patch to resolve the behavior?

**Comment by samsonasik** [comment]
@DASPRiD @weierophinney I've created PR #151 for it
